### ISSUE TITLE
Cannot install gems after update to 2.1.1

### ISSUE THREAD

**Issue by stefanvermaas** [rbenv/rbenv#573]
Hi guys, 

I've ran into a problem, that I couldn't solve. After I installed Ruby 2.1.1 with Rbenv, I can't install any gems anymore. I'm running into this error message:

``` shell
➜  ~  gem install bundler
ERROR:  Loading command: install (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

These are my system specs. I'm on a MacBook Pro running Mavericks.

``` shell
➜  ~  rbenv -v
rbenv 0.4.0
➜  ~  rbenv versions
  system
  2.0.0-p247
  2.0.0-p353
  2.1.0
* 2.1.1 (set by /Users/stefan.vermaas/.rbenv/version)
➜  ~  rbenv global
2.1.1
➜  ~  ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0]
➜  ~  gem -v
2.2.2
```

I've tried to find some anwers on the web, but I could only find "the solution" for other platforms than my Mac. Can you guys help me out?

Cheers.

**Comment by AbhimanyuAryan** [comment]
@stefanvermaas did you fixed the issue? How?

**Comment by stefanvermaas** [comment]
Yeah it did. 

Somehow the zlib package was broken, but it seemed to go further. I couldn't find the real issue, reinstalling homebrew fix it for me.

**Comment by AbhimanyuAryan** [comment]
well i don't know how homebrew re-installation fixed it. That doesn't seem to look like a homebrew problem. Anyways its good to know, that you got it working.

**Comment by stefanvermaas** [comment]
I know. It isn't a good solution, but it had to do with a corrupt library. Though I couldn't find out which lib, so I tried this radical approach, which worked.

**Comment by caiocutrim** [comment]
I have this same problem with latest ruby version, I can't install gems libraries. I am using ubuntu 14.04 and compile this source with build-essencials "./configure, make and sudo make install".

**Comment by davidcpell** [comment]
I am having the same problem on OSX Yosemite 10.10.4. I deleted ruby 2.2.2 with `rm -rf ~/.rbenv/versions/2.2.2` in a desperate attempt to fix another problem I was having (thought I would start over with this ruby installation) and I now I can't even install bundler after reinstalling 2.2.2 with `rbenv install 2.2.2`. 

```
master ✔ $ gem install bundler                                                                                                             1 ↵
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

**Comment by mislav** [comment]
I'm not familiar with the issue of Ruby not compiling with zlib support on OS X. I can only imagine this could happen if you installed some incompatible version of zlib manually on your system. Also, could you check `brew list | grep zlib`?

**Comment by mislav** [comment]
@davidcpell I see you fixed your problem https://github.com/sstephenson/ruby-build/issues/780#issuecomment-118707211

**Comment by davidcpell** [comment]
@mislav yes, it was an issue with Xcode. thanks!
