### ISSUE TITLE
Error while installing ruby in Cygwin

### ISSUE THREAD

**Issue by victorlcampos** [rbenv/rbenv#992]
Hi guys,
Sorry for my English, It's not my native language, I'm trying improve it.

I'm getting this error when I tryed install ruby 2.3.3 on Windows:

ruby.c: In function ‘dladdr_path’:
ruby.c:404:5: error: unknown type name ‘Dl_info’
     Dl_info dli;
     ^
ruby.c:407:10: warning: implicit declaration of function ‘dladdr’ [-Wimplicit-function-declaration]
     if (!dladdr(addr, &dli)) {
          ^
In file included from ./include/ruby/ruby.h:1992:0,
                 from ./include/ruby.h:33,
                 from internal.h:15,
                 from ruby.c:18:

Could you help me?

**Comment by mislav** [comment]
Sorry, this tool is not meant to be used on Windows!

**Comment by allenatdecisiv** [comment]
Hi,

I know this ticket is closed (and dated) but the issue is that one would need the Cygwin patches (or find and fix the issues themselves) for Ruby (there's a patch for the OPs issue) to install it on Cygwin. I used the latest rbenv and it works fine on Cygwin (with Cygwin's 2.3.6 Ruby patches and libssl-1.0/libssl-1.0-devel packages):

```
$ uname -a
CYGWIN_NT-10.0 FOUREYES 3.1.2(0.340/5/3) 2019-12-21 15:25 x86_64 Cygwin
$ rbenv --version
rbenv 1.1.2-11-gc46a970
$ rbenv versions
* 2.3.8 (set by /cygdrive/c/Users/allen/.rbenv/version)
$ ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-cygwin]
```

I haven't used all the rbenv functionaliy or features, but rbenv works fine for me on Cygwin. Nice work @mislav and rbenv Team!
