### ISSUE TITLE
Failed to build Ruby 2.3.0 on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by andisugandi** [rbenv/rbenv#890]
Hi all,

I've never found problem installing ruby via rbenv on openSUSE 13.2 and Leap 42.1, but found one on Tumbleweed:

```
> rbenv install 2.3.0
Downloading ruby-2.3.0.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.3/ruby-2.3.0.tar.bz2
Installing ruby-2.3.0...

BUILD FAILED (openSUSE 20160117 using ruby-build 20160330-6-g28a9ba8)

Inspect or clean up the working tree at /tmp/ruby-build.20160403130635.6106
Results logged to /tmp/ruby-build.20160403130635.6106.log

Last 10 log lines:
 #error "GCC no longer implements <varargs.h>."
  ^
/usr/lib64/gcc/x86_64-suse-linux/5/include/varargs.h:5:2: error: #error "Revise your code to use <stdarg.h>."
 #error "Revise your code to use <stdarg.h>."
  ^
Makefile:375: recipe for target 'dmydln.o' failed
make: *** [dmydln.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:375: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

Here it is a config.log: [config.log.txt](https://github.com/rbenv/rbenv/files/201199/config.log.txt) , and the ruby-build.20160403130635.6106.log: [ruby-build.20160403130635.6106.log.txt](https://github.com/rbenv/rbenv/files/201201/ruby-build.20160403130635.6106.log.txt)

Is it related to https://github.com/rbenv/rbenv/issues/881 and https://github.com/rbenv/ruby-build/issues/805 ?

Any suggestions?

**Comment by andisugandi** [comment]
Trying with:

`RUBY_CONFIGURE_OPTS=--with-opt-dir=/usr/local rbenv install 2.3.0`

the issue still persists.

**Comment by hsbt** [comment]
I confirmed to work with OpenSUSE 13.2 stable environment.

but I don't have tumbleweed environment. It seems to defects of gcc on tumbleweed environment.

**Comment by mislav** [comment]
@andisugandi Thanks for reporting! I myself don't have any suggestions that you can try right now, unfortunately, but ultimately I'd want us to move this issue to ruby-build since that project is responsible for building Rubies on different platforms.
